"""
AUTO-GENERATED FILE - DO NOT EDIT MANUALLY

This file is automatically generated from JSON schemas in the LibreTap/mqtt-protocol repository:
https://github.com/LibreTap/mqtt-protocol/tree/main/schemas

Generated by running: uv run python scripts/generate_mqtt_models.py

To update these models:
1. Update JSON schemas in the mqtt-protocol repository
2. Run: uv run python scripts/generate_mqtt_models.py
3. Commit the regenerated models

Last generated: 2025-11-12 21:41:58 UTC
"""

from __future__ import annotations
from enum import Enum
from ipaddress import IPv4Address
from pydantic import AwareDatetime, BaseModel, Field
from pydantic import BaseModel, Field, RootModel
from typing import Annotated, Any, Literal
from typing import Annotated, Any, Literal, Optional
from typing import Annotated, Any, Optional
from uuid import UUID

# generated by datamodel-codegen:
#   filename:  schemas
#   timestamp: 2025-11-12T21:41:58+00:00

# generated by datamodel-codegen:
#   filename:  commands.json
#   timestamp: 2025-11-12T21:41:58+00:00

class CommandPayloads(RootModel[Any]):
    root: Annotated[
        Any,
        Field(
            description='Payload schemas for commands sent from Service to Device',
            title='Command Payloads',
        ),
    ]

class RegisterStart(BaseModel):
    tag_uid: Annotated[
        str,
        Field(
            description='NFC tag UID in colon-separated hex format',
            pattern='^([0-9A-Fa-f]{2}:)+[0-9A-Fa-f]{2}$',
        ),
    ]
    key: Annotated[
        str,
        Field(
            description='32-character hex encryption key', pattern='^[0-9A-Fa-f]{32}$'
        ),
    ]
    timeout_seconds: Annotated[
        int, Field(description='Operation timeout in seconds', ge=1, le=300)
    ]

class AuthStart(BaseModel):
    timeout_seconds: Annotated[
        int, Field(description='Operation timeout in seconds', ge=1, le=300)
    ]

class UserData(BaseModel):
    """
    User authentication data
    """

    username: Optional[str] = None
    context: Optional[str] = None

class AuthVerify(BaseModel):
    tag_uid: Annotated[
        str,
        Field(
            description='NFC tag UID in colon-separated hex format',
            pattern='^([0-9A-Fa-f]{2}:)+[0-9A-Fa-f]{2}$',
        ),
    ]
    key: Annotated[
        str,
        Field(
            description='32-character hex encryption key', pattern='^[0-9A-Fa-f]{32}$'
        ),
    ]
    user_data: Annotated[UserData, Field(description='User authentication data')]

class ReadBlock(RootModel[int]):
    root: Annotated[int, Field(ge=0, le=255)]

class ReadStart(BaseModel):
    timeout_seconds: Annotated[
        int, Field(description='Operation timeout in seconds', ge=1, le=300)
    ]
    read_blocks: Annotated[
        list[ReadBlock],
        Field(description='Block numbers to read from tag', min_length=1),
    ]

class Cancel(BaseModel):
    """
    Empty payload for cancel operations
    """

class Reset(BaseModel):
    """
    Empty payload for reset command
    """

# generated by datamodel-codegen:
#   filename:  events.json
#   timestamp: 2025-11-12T21:41:58+00:00

class EventPayloads(RootModel[Any]):
    root: Annotated[
        Any,
        Field(
            description='Payload schemas for events sent from Device to Service',
            title='Event Payloads',
        ),
    ]

class Status(Enum):
    online = 'online'
    offline = 'offline'

class StatusChange(BaseModel):
    status: Status
    firmware_version: Annotated[str, Field(pattern='^\\d+\\.\\d+\\.\\d+$')]
    ip_address: IPv4Address

class Mode(Enum):
    idle = 'idle'
    register = 'register'
    auth = 'auth'
    read = 'read'

class PreviousMode(Enum):
    idle = 'idle'
    register = 'register'
    auth = 'auth'
    read = 'read'

class ModeChange(BaseModel):
    mode: Mode
    previous_mode: PreviousMode

class TagDetected(BaseModel):
    tag_uid: Annotated[
        str,
        Field(
            description='NFC tag UID in colon-separated hex format',
            pattern='^([0-9A-Fa-f]{2}:)+[0-9A-Fa-f]{2}$',
        ),
    ]
    message: str

class SuccessRegisterRead(BaseModel):
    tag_uid: Annotated[str, Field(pattern='^([0-9A-Fa-f]{2}:)+[0-9A-Fa-f]{2}$')]
    blocks_written: Annotated[Optional[int], Field(ge=0)] = None
    message: str

class SuccessAuth(BaseModel):
    tag_uid: Annotated[str, Field(pattern='^([0-9A-Fa-f]{2}:)+[0-9A-Fa-f]{2}$')]
    authenticated: Literal[True]
    message: str
    user_data: Optional[dict[str, Any]] = None

class FailedAuth(BaseModel):
    tag_uid: Annotated[str, Field(pattern='^([0-9A-Fa-f]{2}:)+[0-9A-Fa-f]{2}$')]
    authenticated: Literal[False]
    reason: str

class ErrorCode(Enum):
    NFC_TIMEOUT = 'NFC_TIMEOUT'
    NFC_TAG_LOST = 'NFC_TAG_LOST'
    NFC_AUTH_FAILED = 'NFC_AUTH_FAILED'
    NFC_READ_ERROR = 'NFC_READ_ERROR'
    NFC_WRITE_ERROR = 'NFC_WRITE_ERROR'
    NFC_UNSUPPORTED_TAG = 'NFC_UNSUPPORTED_TAG'
    NFC_INVALID_KEY = 'NFC_INVALID_KEY'
    NFC_DEVICE_BUSY = 'NFC_DEVICE_BUSY'
    NFC_DEVICE_ERROR = 'NFC_DEVICE_ERROR'
    INVALID_COMMAND = 'INVALID_COMMAND'
    SESSION_NOT_FOUND = 'SESSION_NOT_FOUND'
    TIMEOUT_EXCEEDED = 'TIMEOUT_EXCEEDED'

class Component(Enum):
    nfc = 'nfc'
    pn532 = 'pn532'
    crypto = 'crypto'
    device = 'device'
    protocol = 'protocol'

class Error(BaseModel):
    error: Annotated[str, Field(description='Human-readable error description')]
    error_code: ErrorCode
    retry_possible: bool
    component: Component

class Heartbeat(BaseModel):
    uptime_seconds: Annotated[int, Field(ge=0)]
    memory_usage_percent: Annotated[float, Field(ge=0.0, le=100.0)]
    operations_completed: Annotated[int, Field(ge=0)]

# generated by datamodel-codegen:
#   filename:  message-envelope.json
#   timestamp: 2025-11-12T21:41:58+00:00

class EventType(Enum):
    """
    Message type
    """

    register_start = 'register_start'
    register_cancel = 'register_cancel'
    register_success = 'register_success'
    register_error = 'register_error'
    auth_start = 'auth_start'
    auth_verify = 'auth_verify'
    auth_cancel = 'auth_cancel'
    auth_tag_detected = 'auth_tag_detected'
    auth_success = 'auth_success'
    auth_failed = 'auth_failed'
    auth_error = 'auth_error'
    read_start = 'read_start'
    read_cancel = 'read_cancel'
    read_success = 'read_success'
    read_error = 'read_error'
    reset = 'reset'
    status_change = 'status_change'
    mode_change = 'mode_change'
    heartbeat = 'heartbeat'

class MqttMessageEnvelope(BaseModel):
    """
    Standard envelope for all MQTT messages in the LibreTap protocol
    """

    version: Annotated[Literal['1.0'], Field(description='Protocol version')]
    timestamp: Annotated[AwareDatetime, Field(description='ISO 8601 UTC timestamp')]
    device_id: Annotated[
        str, Field(description='Device identifier', pattern='^[a-zA-Z0-9_-]+$')
    ]
    event_type: Annotated[EventType, Field(description='Message type')]
    request_id: Annotated[UUID, Field(description='UUID v4 for operation tracking')]
    payload: Annotated[dict[str, Any], Field(description='Event-specific payload data')]
